version: '3.8'

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    environment:
      - TZ=Europe/Madrid
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - /data:/data
    #network_mode: host
