version: '3.8'

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - /nodered/data:/data
    network_mode: host
