version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2023:2023"
    volumes:
      - /influxdb/var/lib/influxdb:/var/lib/influxdb
      - /influxdb/etc/influxdb:/etc/influxdb